/* v15针对性验证：实际传输、分句和会话模块；所有网络/录音是明确的测试替身，无真实Key。 */
const test=require('node:test'), assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
/** 输入：无。输出：隔离模块。功能：加载交付源码，不依赖真实浏览器/账户。 */
function fixture(){const c=vm.createContext({Date,Intl,Math,Map,Set,Object,Array,Number,String,JSON,RegExp,Error,TypeError,Promise,AbortController,DOMException,URL,Response,ReadableStream,TextDecoder,TextEncoder,Uint8Array,performance,console,setTimeout,clearTimeout,fetch:async()=>{throw Error('Unexpected network')},localStorage:{getItem:()=>null,setItem:()=>{}}});vm.runInContext('const __fluffyModules={}',c);for(const n of ['ai-policy','model','sleep-time','catalog','journal-store','review-data','chat-stream','deepseek','chat-text','chat-memory','review-conversation'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/'+n+'.js'),'utf8'),c,{filename:n+'.js'});return{get:n=>vm.runInContext(`__fluffyModules['${n}.js']`,c)}}
const f=fixture(),S=f.get('chat-stream'),T=f.get('chat-text'),M=f.get('chat-memory'),Talk=f.get('review-conversation');
/** 输入：字符串。输出：可测量宽度。功能：纯逻辑测试同时覆盖汉字和拉丁字符。 */
function measure(t){return [...t].reduce((v,c)=>v+(/[\u3400-\u9fff]/.test(c)?13:6.5),0)}
/** 输入：字符串、可选终止原因。输出：SSE协议文本。功能：生成透明的测试网络响应。 */
function wire(text,finish='stop'){return 'data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',content:''}}]})+'\r\n\r\n'+[...text].map(x=>'data: '+JSON.stringify({choices:[{index:0,delta:{content:x},finish_reason:null}]})+'\r\n\r\n').join('')+'data: '+JSON.stringify({choices:[{index:0,delta:{},finish_reason:finish}]})+'\r\n\r\ndata: '+JSON.stringify({choices:[],usage:{completion_tokens:22}})+'\r\n\r\ndata: [DONE]\r\n\r\n'}
/** 输入：协议文本、块大小。输出：Response。功能：在任意字节边界拆块，含中文UTF-8字节内部。 */
function response(text,size=17){const bytes=new TextEncoder().encode(text);let offset=0;return new Response(new ReadableStream({pull(c){if(offset>=bytes.length){c.close();return;}c.enqueue(bytes.slice(offset,offset+size));offset+=size;}}),{headers:{'Content-Type':'text/event-stream'}})}
/** 输入：fetch与超时。输出：真实DeepSeek客户端。功能：模拟边界但不绕过任何生产校验。 */
function client(fetch,timeout=60000){const c=new (f.get('deepseek').DeepSeekClient)({fetchImpl:fetch,requestTimeoutMs:timeout});c.setKey('sk-test-fixture-not-a-real-key');return c}
/** 输入：客户端及可选参数。输出：请求配置。功能：只传人工回顾，不读取用户记录。 */
function args(api,rest={}){return{api,view:f.get('review-data').build('sport','2026-09-22',[]),text:'今天有点累',lang:'zh',measure,width:122,...rest}}
for(const size of [1,2,3,7,17,97,100000])test('SSE任意字节分块保留中文和使用量尾包 '+size,async()=>{let out='';const r=await S.read(response(wire('今天辛苦了。'),size),undefined,x=>out+=x);assert.equal(out,'今天辛苦了。');assert.equal(r.text,out)});
test('忽略reasoning_content，只显示正文',async()=>{const raw='data: '+JSON.stringify({choices:[{index:0,delta:{reasoning_content:'PRIVATE_REASONING'}}]})+'\n\n'+wire('好呀。');let s='';await S.read(response(raw),undefined,x=>s+=x);assert.equal(s,'好呀。')});
test('JSON型兼容响应正文可用，不强制replies结构',async()=>{let t='';await S.read(Response.json({choices:[{finish_reason:'stop',message:{content:'我在这里。'}}]}),null,x=>t+=x);assert.equal(t,'我在这里。')});
for(const [name,raw,code] of [['空正文',wire(''),'ai-empty'],['长度截断',wire('先停一下。后面','length'),'ai-truncated'],['异常终止',wire('我在这里。','insufficient_system_resource'),'ai-incomplete'],['缺结束包','data: {"choices":[{"delta":{"content":"已完整收到。"}}]}\n\n','ai-incomplete'],['JSON坏块','data: {bad}\n\n','ai-format'],['上游错误事件','data: {"error":{"message":"PRIVATE"}}\n\n','ai-incomplete']])test('传输区分 '+name,async()=>await assert.rejects(S.read(response(raw),null,()=>{}),e=>e.code===code&&!e.message.includes('PRIVATE')));
test('挂起reader被取消后立即结束',async()=>{let canceled=false;const c=new AbortController();const r=new Response(new ReadableStream({cancel(){canceled=true}}),{headers:{'Content-Type':'text/event-stream'}});const task=S.read(r,c.signal);setTimeout(()=>c.abort(),5);await assert.rejects(task,e=>e.name==='AbortError');assert.ok(canceled)});
test('流请求没有JSON模式、不向百炼发语言',async()=>{let sent,url;const api=client(async(u,o)=>{url=u;sent=JSON.parse(o.body);return response(wire('慢慢来呀。'))});await Talk.request(args(api));assert.equal(sent.stream,true);assert.equal(sent.response_format,undefined);assert.equal(sent.thinking.type,'disabled');assert.ok(url.startsWith('https://api.deepseek.com'));assert.equal(sent.tools,undefined)});
test('空回复最多补一次，第二次成功',async()=>{let calls=0;const out=[];const api=client(async()=>response(wire(++calls===1?'':'我在认真听。')));await Talk.request(args(api,{onPage:p=>out.push(p)}));assert.equal(calls,2);assert.equal(out.map(p=>p.text).join(''),'我在认真听。')});
test('连续空回复明确失败，没有无限重试',async()=>{let n=0;const api=client(async()=>{n++;return response(wire(''))});await assert.rejects(Talk.request(args(api)),e=>e.code==='ai-empty');assert.equal(n,2)});
test('503只在未输出时恢复一次',async()=>{let n=0;const api=client(async()=>++n===1?new Response('',{status:503,headers:{'Retry-After':'0'}}):response(wire('回来啦。')));await Talk.request(args(api));assert.equal(n,2)});
for(const status of [400,401,402,403,404,422,429])test('不可恢复HTTP不重试或超长Retry-After不抢跑 '+status,async()=>{let n=0;const api=client(async()=>{n++;return new Response('PRIVATE',{status,headers:{'Retry-After':'60'}})});await assert.rejects(Talk.request(args(api)));assert.equal(n,1)});
test('未知网络错误不盲目重复计费请求',async()=>{let n=0;const api=client(async()=>{n++;throw new TypeError('offline')});await assert.rejects(Talk.request(args(api)),e=>e.code==='ai-network');assert.equal(n,1)});
test('流已输出后断开：不重试整段、不发出未完成尾句',async()=>{let n=0;const out=[];const api=client(async()=>{n++;return response(wire('今天已经很努力。还没有讲完','length'))});await assert.rejects(Talk.request(args(api,{onPage:p=>out.push(p.text)})),e=>e.code==='ai-truncated');assert.equal(n,1);assert.equal(out.join(''),'今天已经很努力。')});
test('退避时取消，不开始第二次请求',async()=>{let n=0;const api=client(async()=>{n++;return response(wire(''))}),c=new AbortController();const p=Talk.request(args(api,{signal:c.signal}));setTimeout(()=>c.abort(),30);await assert.rejects(p,e=>e.name==='AbortError');assert.equal(n,1)});
test('总超时涵盖SSE等待，不无限思考',async()=>{const api=client(async()=>new Response(new ReadableStream({}),{headers:{'content-type':'text/event-stream'}}),30);await assert.rejects(Talk.request(args(api)),e=>e.code==='ai-timeout')});
test('第一句出现时流还没结束',async()=>{let ctl,done=false;const out=[];const api=client(async()=>new Response(new ReadableStream({start(c){ctl=c;c.enqueue(new TextEncoder().encode('data: {"choices":[{"index":0,"delta":{"content":"我听到啦。"}}]}\n\n'));}}),{headers:{'content-type':'text/event-stream'}}));const p=Talk.request(args(api,{onPage:v=>out.push(v.text)})).then(()=>done=true);await new Promise(r=>setTimeout(r,20));assert.equal(out[0],'我听到啦。');assert.equal(done,false);ctl.enqueue(new TextEncoder().encode(wire('慢慢来。')));ctl.close();await p;assert.equal(out.join(''),'我听到啦。慢慢来。')});
for(const raw of ['{"replies":["我在听呀。","你慢慢说。"]}','{"replies":[{"text":"我在听呀。"}]}','["我在听呀。"]','```json\n{"replies":[{"text":"我在听呀。","gesture":"unknown"}]}\n```'])test('旧式结构兼容，不因无动作丢回复 '+raw.slice(0,25),()=>{const out=[],b=new T.PhraseBuffer({onPage:x=>out.push(x)});for(const c of raw)b.push(c);assert.equal(out.length,0);b.finish();assert.ok(out.length>0);assert.ok(out[0].text.includes('我在听呀'));});
const samples=['今天这十二分钟，也是认真付出呀。','这段话很长但是没有标点我们还是应该让每个气泡有最多十六个可见字符并保留全部文字','不用赶着好起来，我会在这里认真听你说。','今天跑了3.5公里，已经很认真啦。','23:00到07:00睡了8小时。','今天有点失落，但并不是很难过。','今天😺也在这里，陪你慢慢走。','不用急着告诉我答案。','You made time for yourself. That matters.','I didn’t mean that you need to run 3.5 km.','Averylongunbrokenwordshouldneveroverflowthebubble','今天跑了12 min，感觉还不错呢。'];
for(const sample of samples)test('分句16字/两行/不丢字 '+sample.slice(0,18),()=>{const zh=/[\u3400-\u9fff]/.test(sample),rows=T.pages(sample,measure,122,zh?'zh':'en');assert.equal(rows.flat().join('').replace(/\s/g,''),sample.replace(/\s/g,''));for(const row of rows){assert.ok(row.length<=2);assert.ok(row.every(x=>measure(x)<=122));if(zh)assert.ok(T.count(row.join(''))<=16)}});
test('数字与单位在同一页不拆开',()=>{const out=T.pages('今天跑了3.5公里，已经很认真啦。',measure,122,'zh').map(x=>x.join(''));assert.ok(out.some(x=>x.includes('3.5公里')))});
test('英文页面收到中文不会显示中文，返回语言故障',()=>{const out=[],b=new T.PhraseBuffer({lang:'en',onPage:x=>out.push(x)});assert.throws(()=>b.push('中文不能显示。'),e=>e.code==='language-reply');assert.equal(out.length,0)});
test('流式单字符中文分块，显示片段仍是完整句',()=>{const out=[],b=new T.PhraseBuffer({onPage:x=>out.push(x)});for(const c of '我在听你说')b.push(c);assert.equal(out.length,0);b.push('。');assert.equal(out.length,1);b.finish();assert.equal(out[0].text,'我在听你说。')});
test('结束前取消分句器，不吐出未完成的后半句',()=>{const out=[],b=new T.PhraseBuffer({onPage:x=>out.push(x)});b.push('先听到这句。还没');b.cancel();b.push('完的话。');assert.equal(out.length,1)});
test('缓冲中小数点不误当句号',()=>{const out=[],b=new T.PhraseBuffer({onPage:x=>out.push(x)});b.push('跑了3.');assert.equal(out.length,0);b.push('5公里。');b.finish();assert.equal(out.map(x=>x.text).join(''),'跑了3.5公里。')});
test('用户原话在请求失败前就保留，未说出的回答不进入上下文',()=>{const m=new M.ConversationMemory(),t=m.begin('刚才有些累');m.finish(t,'failed');assert.equal(m.messages()[0].content,'刚才有些累');assert.equal(m.messages().length,1)});
test('中途打断，只提交已上屏的第一句',()=>{const m=new M.ConversationMemory(),t=m.begin('十二分钟够吗');m.present(t,0,'这也是认真付出呀。');m.finish(t,'interrupted');const ctx=JSON.stringify(m.context());assert.ok(ctx.includes('这也是认真付出呀'));assert.ok(ctx.includes('interrupted'));assert.ok(!ctx.includes('你是时间不够还是身体累'))});
test('重试沿用逻辑ID，用户原话只出现一次',()=>{const m=new M.ConversationMemory(),t=m.begin('我想聊聊');m.finish(t,'failed');const r=m.begin('我想聊聊',false,t.id);assert.equal(r.id,t.id);assert.equal(m.messages().filter(x=>x.role==='user').length,1)});
test('用户有意说两次同一句仍是两轮',()=>{const m=new M.ConversationMemory();m.begin('你好');m.begin('你好');assert.equal(m.messages().filter(x=>x.role==='user').length,2)});
test('反复渲染同一页不重复写历史',()=>{const m=new M.ConversationMemory(),t=m.begin('你好');m.present(t,0,'我在听。');m.present(t,0,'我在听。');assert.equal(t.presented.length,1)});
test('200轮上下文受限、近期完整、早期只存有标记摘录',()=>{const m=new M.ConversationMemory();for(let i=0;i<200;i++){const t=m.begin('问题'+i+'内容'.repeat(300));m.present(t,0,'答复'+i);m.finish(t,'complete')}assert.equal(m.turns.length,40);const ctx=m.context();assert.ok(JSON.stringify(ctx).length<17000);assert.ok(ctx.messages.some(x=>x.content.startsWith('问题199')));assert.ok(ctx.earlierExcerpts.length<=8)});
test('新轮请求只带已显示历史，当前问题只追加一次',async()=>{const m=new M.ConversationMemory(),t=m.begin('我时间不够');m.present(t,0,'那就从小步开始。');m.finish(t,'interrupted');const current=m.begin('今天先做什么');let body;const api=client(async(u,o)=>{body=JSON.parse(o.body);return response(wire('先挑一件小事。'))});await Talk.request(args(api,{memory:m.context(current.id),text:current.text}));assert.equal(body.messages.filter(x=>x.content===current.text).length,1);assert.ok(body.messages.some(x=>x.content==='那就从小步开始。'));assert.ok(body.messages[1].content.includes('interrupted'))});
test('诊断只能保存白名单数值，不保存原文密钥',()=>{const d=new M.Diagnostics();for(let i=0;i<200;i++)d.add(i,'request',{characters:16,text:'SECRET_TEXT',key:'sk-SECRET',code:'ai-empty'});d.add(1,'SECRET_EVENT');assert.equal(d.snapshot().length,120);assert.ok(!JSON.stringify(d.snapshot()).includes('SECRET'))});
