/* v8 日期/回顾/语言回归：实际源码，隔离存储，不调用网络。 */
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
/** 输入：无。输出：模块与隔离存储。功能：执行交付代码的纯逻辑，不另写被测实现。 */
function setup(){const storage=new Map(),ctx=vm.createContext({Date,Intl,JSON,Math,Map,Set,Object,Array,Number,String,Error,console,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v))}});vm.runInContext('const __fluffyModules={}',ctx);for(const n of ['ai-policy','model','sleep-time','catalog','journal-store','review-data','chat-text','review-conversation','entry-i18n'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/'+n+'.js'),'utf8'),ctx);return{ctx,get:n=>vm.runInContext(`__fluffyModules["${n}.js"]`,ctx),storage};}
/** 输入：类别、日期与ID。输出：人工测试记录。功能：样例只在测试内生成，绝不打入发布网页。 */
function fixture(category,recordDate,id=category){const data={sport:{activity:'力量训练',durationMinutes:25,notes:'4组深蹲'},food:{meal:'午餐',foods:'米饭和鸡肉',portion:'一碗',calories:500,protein:20,carbs:60,fat:10},mood:{mood:'放松又有点累',reason:'刚做完实验',notes:'慢慢来'},face:{feeling:'精神还好',eyeArea:'眼周阴影',skinAppearance:'光线偏暗'},sleep:{bedtime:'23:00',wakeTime:'07:00',quality:'醒来舒服',notes:'中途没醒'},focus:{task:'读论文',durationMinutes:25,notes:'方法部分'}}[category];return{id,category,recordDate,data,createdAt:new Date().toISOString(),source:'manual',...(category==='focus'?{focus:{elapsedMs:15*60000,restMs:2*60000}}:{})};}
for(const id of ['sport','food','mood','sleep','face','focus'])test(`${id}补记归入所选日，创建日期不伪造`,()=>{const f=setup(),S=f.get('journal-store'),D=f.get('review-data'),r=fixture(id,'2026-09-18');assert.equal(S.save(r),true);const saved=S.records()[0];assert.equal(saved.createdAt,r.createdAt);assert.equal(S.dateOf(saved),'2026-09-18');assert.equal(D.build(id,'2026-09-18').today.count,1);assert.equal(D.build(id,S.dayKey()).today.count,0);assert.equal(S.stats().today,0);assert.equal(S.stats().days,1);assert.equal(D.context(D.build(id,'2026-09-18')).confirmedRecords[0].date,'2026-09-18');});
test('补记新建记录不会替代今日已有记录',()=>{const f=setup(),S=f.get('journal-store');S.save(fixture('sport',S.dayKey(),'today'));S.save(fixture('sport','2025-12-31','past'));assert.equal(S.records()[0].id,'today');assert.equal(S.records().length,2);assert.equal(S.stats().today,1);});
test('修改同一ID日期只迁移该记录，不重复保存',()=>{const f=setup(),S=f.get('journal-store'),D=f.get('review-data'),r=fixture('sport','2026-09-18');S.save(r);S.save({...r,recordDate:'2026-09-17'});assert.equal(S.records().length,1);assert.equal(D.build('sport','2026-09-18').today.count,0);assert.equal(D.build('sport','2026-09-17').today.count,1);assert.equal(S.records()[0].createdAt,r.createdAt);});
test('旧记录按原创建的本地日兼容，读取不改写磁盘',()=>{const f=setup(),S=f.get('journal-store'),r=fixture('sport',undefined);delete r.recordDate;const raw=JSON.stringify([r]);f.storage.set(S.KEY,raw);assert.equal(S.dateOf(S.records()[0]),S.dayKey(new Date(r.createdAt)));assert.equal(f.storage.get(S.KEY),raw);});
test('旧睡眠记录按醒来日恢复，而不是创建日',()=>{const f=setup(),S=f.get('journal-store'),C=f.get('catalog');const r=fixture('sleep',undefined);delete r.recordDate;r.data=C.validate('sleep',r.data,true,{recordDate:'2025-12-31'}).value;f.storage.set(S.KEY,JSON.stringify([r]));assert.equal(S.records()[0].recordDate,'2025-12-31');assert.equal(S.records()[0].data.hours,8);});
test('非法日期和未来日期拒绝保存',()=>{const f=setup(),S=f.get('journal-store'),T=f.get('sleep-time');for(const d of ['2026-02-30','2026-13-01',T.addDays(S.dayKey(),1)])assert.equal(S.save(fixture('sport',d)),false);assert.equal(S.records().length,0);});
test('睡眠补记跨年：23到07以所选醒来日为准',()=>{const f=setup(),S=f.get('journal-store');S.save(fixture('sleep','2026-01-01'));const r=S.records()[0];assert.equal(r.data.bedDate,'2025-12-31');assert.equal(r.data.wakeDate,'2026-01-01');assert.equal(r.data.hours,8);});
test('凌晨睡眠补记不额外减一天',()=>{const f=setup(),S=f.get('journal-store'),r=fixture('sleep','2024-02-29');r.data.bedtime='01:00';S.save(r);assert.equal(S.records()[0].data.bedDate,'2024-02-29');assert.equal(S.records()[0].data.hours,6);});
test('日期统计按事件日，多个类别只算一次陪伴日',()=>{const f=setup(),S=f.get('journal-store');S.save(fixture('sport','2026-09-18'));S.save(fixture('food','2026-09-18'));assert.equal(S.stats().days,1);assert.equal(S.stats().count,2);});
test('没有数据的六个板块也有空回顾',()=>{const f=setup(),D=f.get('review-data');for(const id of ['sport','food','mood','sleep','face','focus']){const view=D.build(id,'2026-09-18',[]);assert.equal(view.week.length,7);assert.equal(view.today.score,null);assert.equal(view.today.count,0);assert.equal(view.records.length,0);}});
test('手动补记专注不伪造计划或计时分数',()=>{const f=setup(),S=f.get('journal-store'),D=f.get('review-data'),r=fixture('focus','2026-09-18');r.focus={elapsedMs:25*60000,restMs:0,plannedMs:null,provenance:'self-reported'};S.save(r);const view=D.build('focus','2026-09-18');assert.equal(view.today.value,25);assert.equal(view.today.score,null);assert.equal(D.context(view).confirmedRecords[0].actualFocus.provenance,'self-reported');});
test('历史回顾传给AI日期及historical明确，不当成今天',()=>{const f=setup(),D=f.get('review-data'),T=f.get('review-conversation');const ctx=D.context(D.build('sport','2026-09-18',[]));assert.equal(ctx.historical,true);assert.equal(ctx.date,'2026-09-18');assert.ok(T.prompt('zh',false,false).includes('不要把那天的事情误称今天'));});
test('界面词典双语持久化，不翻译未知用户文字',()=>{const f=setup(),L=f.get('entry-i18n');assert.equal(L.language(),'zh');L.setLanguage('en');assert.equal(L.t('运动项目'),'Activity');assert.equal(L.t('我的原话保持原样'),'我的原话保持原样');assert.equal(f.storage.get(L.KEY),'"en"');L.setLanguage('zh');assert.equal(L.t('运动项目'),'运动项目');});
test('六类别历史标题不称今天且日期格式使用本地日',()=>{const f=setup(),L=f.get('entry-i18n');for(const id of ['sport','food','mood','sleep','face','focus']){assert.ok(!L.title(id,true).includes('今天'));L.setLanguage('en');assert.ok(!L.title(id,true).includes('today'));L.setLanguage('zh');}assert.ok(L.dateLabel('2026-01-01').includes('1'));});
test('存储写入失败不得虚报成功',()=>{const f=setup(),S=f.get('journal-store');vm.runInContext('localStorage.setItem=()=>{throw new Error("storage quota")}',f.ctx);assert.equal(S.save(fixture('sport','2026-09-18')),false);assert.equal(S.records().length,0);});
test('非法创建时间拒绝保存',()=>{const f=setup(),S=f.get('journal-store');assert.equal(S.save({...fixture('sport','2026-09-18'),createdAt:'bad'}),false);});

test('修改专注实际时长后仍使用原计划作分母',()=>{const f=setup(),S=f.get('journal-store'),D=f.get('review-data'),r=fixture('focus','2026-09-18');r.data.durationMinutes=24;r.focus={elapsedMs:24*60000,restMs:0,plannedMs:30*60000,provenance:'timer'};S.save(r);const view=D.build('focus','2026-09-18');assert.equal(view.today.value,24);assert.equal(view.today.score,80);});
