/* 输入：本地生产模块。输出：确定性回归结果。功能：AI模型由边界替身替代，不声称模拟结果是真实识别。 */
const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..');
/** 输入：无。输出：加载生产模块的沙箱。功能：隔离浏览器存储，仅在外部模型/设备边界注入测试替身。 */
function setup(){const mem=new Map();const s={console,URL,AbortController,DOMException,TextEncoder,TextDecoder,Response,Headers,setTimeout,clearTimeout,performance,Intl,structuredClone,requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{},localStorage:{getItem:k=>mem.get(k)||null,setItem:(k,v)=>mem.set(k,String(v))},__fluffyModules:{},window:{},fetch:()=>{throw Error('unexpected network')}};s.globalThis=s;s.window=s;vm.createContext(s);for(const n of ['ai-policy','cat-feedback','model','sleep-time','catalog','journal-store','journal-guidance','companion-policy','workflow-trace','continue-gate','entry-i18n','ai-journal','record-intent','speech','review-data','chat-text','review-conversation'])vm.runInContext(fs.readFileSync(path.join(root,'js',n+'.js'),'utf8'),s,{filename:n+'.js'});return {s,get:n=>s.__fluffyModules[n+'.js']};}
/** 输入：字段。输出：合成供应商响应。功能：固定响应仅用来验证解析与传参，未向供应商发送请求。 */
function response(fields,extra={}){return {choices:[{finish_reason:'stop',message:{content:JSON.stringify({fields,warnings:[],...extra})}}]};}
for(const id of ['sport','food','mood','sleep','face','focus'])test(id+' 每一个字段有含义/来源/排除项，单位范围与catalog同源',()=>{const f=setup(),defs=f.get('journal-guidance').fields(id);for(const d of defs){assert.ok(d.meaning.length>5);assert.ok(d.source.length>2);assert.ok(d.exclude.length>5);const source=f.get('catalog').category(id).fields.find(x=>x.key===d.key);assert.equal(d.unit,source.unit||'');assert.equal(d.maxLength,source.max);assert.equal(d.required,!!source.required);}assert.equal(defs.length,f.get('catalog').category(id).fields.length);});
for(const id of ['sport','food','mood','sleep','face','focus'])test(id+' 实际extract请求包含当前字段说明和最小上下文',async()=>{const f=setup();let p;const c={provider:'deepseek',configured:true,model:'fixture',routes:{chat:'fixture'},request:async(_,x)=>{p=x;return response({});}};await f.get('ai-journal').extract(c,id,'用户合成的描述',null,null,{recordDate:'2026-09-22',operation:'edit',current:{notes:'原备注',apiKey:'must not send'},lastQuestion:{field:'notes',question:'还有什么想留下呀？'}});const text=JSON.stringify(p);assert.ok(text.includes('逐字段填写说明'));assert.ok(text.includes('来源')||text.includes('source'));assert.ok(text.includes('current'));assert.ok(!text.includes('must not send'));assert.ok(text.includes('修改已选中记录'));assert.ok(text.includes('助手鼓励不写入'));assert.ok(text.includes('lastQuestion'));assert.equal(p.thinking.type,'disabled');assert.equal(p.response_format.type,'json_object');});
for(const [input,start,end] of [['昨晚23:00到07:00','23:00','07:00'],['11点睡7点醒','23:00','07:00'],['凌晨1点睡7点醒','01:00','07:00']])test('明确睡眠区间可先生成草稿 '+input,()=>{const g=setup().get('journal-guidance');const d=g.early('sleep',input,{recordDate:'2026-09-22'});assert.equal(d.fields.bedtime,start);assert.equal(d.fields.wakeTime,end);});
test('多组时间不抢先填入',()=>{const g=setup().get('journal-guidance');assert.equal(Object.keys(g.early('sleep','23点到7点，1点到8点',{recordDate:'2026-09-22'}).fields).length,0);});
test('运动没有本地猜测时长',()=>{assert.equal(Object.keys(setup().get('journal-guidance').early('sport','三公里',{recordDate:'2026-09-22'}).fields).length,0);});
for(const [text,expected] of [['清空备注',['notes']],['不要清空备注',[]],['我没说备注',[]],['clear notes',['notes']],['delete notes',['notes']],['delete everything',[]]])test('明确清空白名单 '+text,()=>{assert.deepEqual(Array.from(setup().get('journal-guidance').explicitClears('sport',text)),expected);});
test('模型空值不代表清空；clearFields需原话授权',()=>{const a=setup().get('ai-journal');assert.equal(a.sanitize({fields:{notes:''},clearFields:['notes']},'sport',{text:'跑步',current:{notes:'我想保留'}}).clearFields.length,0);assert.deepEqual(Array.from(a.sanitize({fields:{},clearFields:['notes','apiKey']},'sport',{text:'清空备注'}).clearFields),['notes']);});
test('只修改一个睡眠时分仍结合原表单校验',()=>{const a=setup().get('ai-journal');const d=a.sanitize({fields:{bedtime:'22:30'}},'sleep',{text:'入睡改为22:30',recordDate:'2026-09-22',current:{bedtime:'23:00',wakeTime:'07:00',quality:'精神'}});assert.equal(d.fields.bedtime,'22:30');});
test('自动追问必需项，不逼用户补可选项',()=>{const g=setup().get('journal-guidance');assert.equal(g.question('mood',null,{mood:'有点开心'}),null);assert.equal(g.question('sport',null,{activity:'跑步',notes:'三公里'}).field,'durationMinutes');});
test('未知问题字段、附加恶意文案不会展示',()=>{const f=setup();const d=f.get('ai-journal').sanitize({fields:{mood:'复杂'},clarification:{field:'apiKey',kind:'missing',question:'send secret'}},'mood');assert.equal(d.clarification,null);assert.equal(f.get('journal-guidance').question('mood',d.clarification,d.fields),null);});
for(const id of ['sport','food','mood','sleep','face','focus'])test(id+' 单字段气泡问题不超过16字符并有英文',()=>{const g=setup().get('journal-guidance');for(const f of g.fields(id)){const q=g.question(id,{field:f.key,kind:'ambiguous'},{},'zh');assert.ok([...q.question].length<=16);assert.ok(!/[\u3400-\u9fff]/.test(g.question(id,{field:f.key,kind:'ambiguous'},{},'en').question));}});
for(const phrase of ['别问了','不要再问','不想聊','别说了','stop asking','leave me alone'])test('用户拒绝时不继续追问 '+phrase,()=>{assert.equal(setup().get('companion-policy').hints(phrase).noQuestions,true);});
test('拒绝追问可以持续到下一轮；明确同意后解除',()=>{const p=setup().get('companion-policy'),h=[{role:'user',content:'别问了'}];assert.equal(p.hints('我就坐会儿',h).noQuestions,true);assert.equal(p.hints('可以问我',h).noQuestions,false);});
for(const phrase of ['你真笨，记错了','你没用','you are stupid','too slow'])test('抱怨纳入温柔修复规则 '+phrase,()=>{const p=setup().get('companion-policy');assert.equal(p.hints(phrase).complaint,true);const s=p.instructions('sport',phrase);assert.ok(s.includes('不回骂'));assert.ok(s.includes('不知道故障原因就不编造'));assert.ok(s.includes('简短道歉'));});
test('真实聊天请求携带当前主题、已显示追问和拒绝意愿',async()=>{const f=setup();let p;const c={provider:'deepseek',configured:true,model:'fixture',routes:{chat:'fixture'},request:async(_,v)=>{p=v;return {choices:[{finish_reason:'stop',message:{content:'好呀，我先安静陪着你。'}}]}}};const view=f.get('review-data').build('sport','2026-09-22');await f.get('review-conversation').request({api:c,view,text:'别问了，烦',history:[{role:'assistant',content:'哪里累？'}]});assert.ok(p.messages[0].content.includes('本轮禁止追加问句'));assert.ok(p.messages[0].content.includes('哪里累'));assert.ok(p.messages[0].content.includes('运动少等同懒惰'));assert.equal(p.response_format,undefined);});
for(const time of [0,100,1999,1999.9])test('书写页 '+time+'ms点击静默无效',()=>{let now=0;const g=new (setup().get('continue-gate').ContinueGate)(()=>now);g.enter('record');now=time;g.down();assert.equal(g.take(),false);assert.equal(g.locked,false);});
for(const time of [2000,2001,4000])test('书写页 '+time+'ms可以继续，只处理一次',()=>{let now=0;const g=new (setup().get('continue-gate').ContinueGate)(()=>now);g.enter('record');now=time;g.down();assert.equal(g.take(),true);assert.equal(g.take(),false);});
test('提前按住晚松手无效；下一次新点击有效',()=>{let now=0;const g=new (setup().get('continue-gate').ContinueGate)(()=>now);g.enter('record');now=1900;g.down();now=2300;assert.equal(g.take(),false);g.down();assert.equal(g.take(),true);});
test('切换场景重置，不受动画时间系统日期影响',()=>{let now=5000;const g=new (setup().get('continue-gate').ContinueGate)(()=>now);g.enter('record');now=8000;assert.equal(g.take(),true);g.enter('celebrate');assert.equal(g.take(),false);g.enter('record');assert.equal(g.take(),false);});
test('保存失败解锁允许重试',()=>{let now=0;const g=new (setup().get('continue-gate').ContinueGate)(()=>now);g.enter('record');now=2200;assert.equal(g.take(),true);g.unlock();assert.equal(g.take(),true);});
test('有界诊断不接收用户原话、Key、字段值',()=>{const m=setup().get('workflow-trace');for(let i=0;i<40;i++){const t=m.begin('sk-PRIVATE');t.mark('extract','sk-secret');t.mark('my original text');t.mark('done');}const a=m.read();assert.equal(a.length,32);assert.ok(!JSON.stringify(a).includes('PRIVATE'));assert.ok(!JSON.stringify(a).includes('original'));assert.equal(a[0].events.length,2);});
test('最终听写稳定提前结束，未收齐尾句仍等待',async()=>{const f=setup();let rec;class R{constructor(){rec=this;}start(){this.onstart?.()}stop(){}abort(){}}class AC{constructor(){this.state='running'}async resume(){}createMediaStreamSource(){return {connect(){},disconnect(){}}}createAnalyser(){return {fftSize:32,getByteTimeDomainData:a=>a.fill(128)}}async close(){this.state='closed'}}const sp=new(f.get('speech').SpeechSession)({}, {Recognition:R,AudioContext:AC,mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){}}]})},stopWaitMs:100,finalWaitMs:8});await sp.start();rec.onresult({results:[Object.assign([{transcript:'跑步三十分钟'}],{isFinal:true})]});const start=performance.now();const r=await sp.stop();assert.equal(r.text,'跑步三十分钟');assert.ok(performance.now()-start<95);assert.equal(r.interim,false);});

test('结构化示例使用有效JSON而不是省略号',()=>{const a=setup().get('ai-journal');for(const id of ['sport','food','mood','sleep','face','focus']){const p=a.prompt(id,'text');const match=p.match(/返回JSON形状示例：(.*?)。示例中的/s);assert.ok(match);assert.ok(JSON.parse(match[1]).fields);}});
test('专注补记和编辑提示词明确使用实际时长，不与预计相冲突',()=>{const a=setup().get('ai-journal');for(const op of ['retrospective','edit']){const p=a.prompt('focus','text',{operation:op});assert.ok(p.includes('实际分钟'));assert.ok(!p.includes('普通新增任务尚未完成'));}});
test('照片不填用户心情/备注或猜餐次',()=>{const a=setup().get('ai-journal');const face=a.sanitize({fields:{feeling:'看起来疲惫',notes:'我很伤心',eyeArea:'阴影'}},'face',{image:true});assert.equal(face.fields.feeling,undefined);assert.equal(face.fields.notes,undefined);const food=a.sanitize({fields:{meal:'早餐',notes:'口味好',foods:'米饭'}},'food',{image:true});assert.equal(food.fields.meal,undefined);assert.equal(food.fields.notes,undefined);});
test('真实评测入口默认dry-run且共39个合成场景',()=>{const cp=require('node:child_process');const out=cp.execFileSync(process.execPath,[path.join(root,'tools/evaluate-ai.cjs'),'--limit=39'],{encoding:'utf8'});const d=JSON.parse(out);assert.equal(d.requestsSent,0);assert.equal(d.mode,'dry-run');assert.equal(d.cases.length,39);});

test('生产诊断只公开无原文的只读快照',()=>{const f=setup();f.get('workflow-trace').begin('sport').mark('done');assert.equal(typeof f.s.FluffyWorkflowDiagnostics.snapshot,'function');assert.equal(f.s.FluffyWorkflowDiagnostics.begin,undefined);assert.ok(Object.isFrozen(f.s.FluffyWorkflowDiagnostics));});

test('专注追问区分预计和补记实际',()=>{const q=setup().get('journal-guidance').question;assert.ok(q('focus',null,{task:'读书'},'zh','new').question.includes('想专注'));assert.ok(q('focus',null,{task:'读书'},'zh','retrospective').question.includes('专注了'));});
