/* v11 回归：全部使用真实模块及隔离数据，API 响应明确为测试替身。 */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
/** 输入：无。输出：隔离模块/存储。功能：避免读写真实浏览器记录或调用付费接口。 */
function fixture(){const storage=new Map(),ctx=vm.createContext({Date,Intl,Math,Map,Set,Object,Number,String,Array,JSON,Error,TypeError,Promise,AbortController,DOMException,URL,setTimeout,clearTimeout,console,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v))}});vm.runInContext('const __fluffyModules={};',ctx);for(const n of ['ai-policy','model','sleep-time','catalog','journal-store','review-data','chat-text','review-conversation','entry-i18n','locale-ui','display-language','record-intent','ai-journal','entry-action'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/'+n+'.js'),'utf8'),ctx);return{get:n=>vm.runInContext(`__fluffyModules['${n}.js']`,ctx),storage};}
/** 输入：类别、编号、字段、附加元数据。输出：有效测试记录。功能：只创建隔离测试条目。 */
function entry(cat,id,data,extra={}){return{id,category:cat,recordDate:'2026-09-22',createdAt:`2026-09-22T${id==='a'?'08':'18'}:00:00`,data,...extra};}
/** 输入：值。输出：JSON兼容副本。功能：跨VM比较不受原型不同影响。 */
function plain(v){return JSON.parse(JSON.stringify(v));}
/** 输入：有效数据。输出：模拟Chat协议响应。功能：清晰标记测试替身，不能当真实API验证。 */
function result(data){return{choices:[{finish_reason:'stop',message:{content:JSON.stringify(data)}}]};}
const fields={sport:{activity:'跑步',durationMinutes:12,notes:'状态不错'},food:{meal:'午餐',foods:'米饭',portion:'一碗',calories:500,protein:20,carbs:50,fat:10,notes:''},sleep:{bedtime:'23:00',wakeTime:'07:00',quality:'很精神',notes:''},mood:{mood:'平静',reason:'休息了',notes:''},face:{feeling:'状态不错',eyeArea:'少许阴影',skinAppearance:'',notes:''},focus:{task:'Read',durationMinutes:20,notes:''}};
for(const cat of Object.keys(fields))test(cat+' 今日保存后进回顾，昨日和草稿不触发',()=>{const f=fixture(),I=f.get('record-intent'),a=entry(cat,'a',fields[cat]);assert.equal(I.destination(cat,'2026-09-22',[]),'entry');assert.equal(I.destination(cat,'2026-09-22',[a]),'review');assert.equal(I.destination(cat,'2026-09-23',[a]),'entry');});
for(const cat of Object.keys(fields))test(cat+' 新增保留原条，编辑不增加数量，保留修订',()=>{const f=fixture(),S=f.get('journal-store');assert.equal(S.save(entry(cat,'a',fields[cat])),true);assert.equal(S.save(entry(cat,'b',fields[cat])),true);const old=S.records().find(r=>r.id==='a'),before=JSON.stringify(S.records().find(r=>r.id==='b'));assert.equal(S.save({...old,expectedUpdatedAt:old.updatedAt,data:{...old.data,notes:'new note'}}),true);assert.equal(S.records().length,2);const saved=S.records().find(r=>r.id==='a');assert.equal(saved.createdAt,old.createdAt);assert.equal(saved.data.notes,'new note');assert.equal(saved.revisions.length,1);assert.equal(JSON.stringify(S.records().find(r=>r.id==='b')),before);});
test('多个标签页修改同条的旧快照不能覆盖',()=>{const S=fixture().get('journal-store');S.save(entry('sport','a',fields.sport));const old=S.records()[0];assert.ok(S.save({...old,expectedUpdatedAt:old.updatedAt,data:{...old.data,durationMinutes:30}}));assert.equal(S.save({...old,expectedUpdatedAt:old.updatedAt,data:{...old.data,durationMinutes:99}}),false);assert.equal(S.records()[0].data.durationMinutes,30);});
test('错误目标ID编辑不降级为插入',()=>{const S=fixture().get('journal-store');assert.equal(S.save({...entry('sport','missing',fields.sport),expectedUpdatedAt:'2026-09-22T00:00:00Z'}),false);assert.equal(S.records().length,0);});
test('运动修改重算总时长，首页统计按类别而非记录次数',()=>{const f=fixture(),S=f.get('journal-store'),D=f.get('review-data');S.save(entry('sport','a',fields.sport));S.save(entry('sport','b',{...fields.sport,durationMinutes:20}));assert.equal(D.build('sport','2026-09-22').today.value,32);let r=S.records()[0];S.save({...r,data:{...r.data,durationMinutes:30}});assert.equal(D.build('sport','2026-09-22').today.value,42);assert.equal(S.stats().count,2);});
test('饮食多餐加总已知数据，不把未知蛋白质当成测得的0',()=>{const D=fixture().get('review-data');const d=D.daily('food',[entry('food','a',fields.food),entry('food','b',{meal:'晚餐',foods:'面',calories:300})],D.goals());assert.equal(d.value,800);assert.equal(d.macros.protein,20);assert.equal(d.count,2);});
test('专注合并实际计时，休息与未完成计划分离',()=>{const D=fixture().get('review-data');const d=D.daily('focus',[entry('focus','a',fields.focus,{focus:{elapsedMs:10*60000,plannedMs:20*60000,restMs:5*60000}}),entry('focus','b',fields.focus,{focus:{elapsedMs:15*60000,plannedMs:20*60000,restMs:0}})],D.goals());assert.equal(d.value,25);assert.equal(d.planned,40);assert.equal(d.restMinutes,5);});
for(const [times,hours,overlaps]of [[['23:00','07:00','13:00','14:00'],9,false],[['23:00','07:00','01:00','08:00'],9,true],[['23:00','07:00','23:00','07:00'],8,true],[['01:00','07:00','07:00','08:00'],7,false]])test('睡眠区间 '+times.join('/'),()=>{const D=fixture().get('review-data'),r=D.sleepTotal([entry('sleep','a',{bedtime:times[0],wakeTime:times[1]}),entry('sleep','b',{bedtime:times[2],wakeTime:times[3]})]);assert.equal(r.hours,hours);assert.equal(r.overlaps,overlaps);});
for(const cat of ['mood','face'])test(cat+' 晨晚变化均保留，最新状态与旧状态不相加',()=>{const D=fixture().get('review-data'),k=cat==='mood'?'mood':'feeling';const d=D.daily(cat,[entry(cat,'a',{...fields[cat],[k]:'早上的感受'}),entry(cat,'b',{...fields[cat],[k]:'晚上的感受'})],D.goals());assert.equal(d.count,2);assert.equal(d.text,'晚上的感受');if(cat==='mood')assert.equal(d.score,null);});
const utterances=[['下午又跑了二十分钟。','add'],['刚才写成二十分钟了，其实是三十分钟。','edit'],['今天很累，想歇一会儿。','none'],['不要修改记录，只是想聊天。','none'],['帮我改成三十分钟。','ask'],['下午又跑了，刚才写错了。','ask'],['早上有点难过，现在好多了。','add'],['Add another workout','add'],['Correct the last entry to thirty minutes','edit'],["Don't edit anything",'none'],['Now feeling more relaxed','add']];
for(const [text,op]of utterances)test('意图 '+text,()=>{const I=fixture().get('record-intent'),r=I.classify(text,{category:'sport',date:'2026-09-22',records:[entry('sport','a',fields.sport),entry('sport','b',fields.sport)]});assert.equal(r.operation,op);});
test('修改午餐只匹配午餐，不能覆盖晚餐',()=>{const I=fixture().get('record-intent'),r=I.classify('午餐份量填错了，是半碗',{category:'food',date:'2026-09-22',records:[entry('food','a',fields.food),entry('food','b',{...fields.food,meal:'晚餐'})]});assert.equal(r.operation,'edit');assert.deepEqual(plain(r.targetIds),['a']);});
test('明确编辑入口优先于最新记录',()=>{const I=fixture().get('record-intent'),r=I.classify('时间改为30分钟',{category:'sport',date:'2026-09-22',editingId:'a',records:[entry('sport','a',fields.sport),entry('sport','b',fields.sport)]});assert.deepEqual(plain(r.targetIds),['a']);});
test('模型不能指定不存在的记录ID或删除',()=>{const I=fixture().get('record-intent'),rows=[entry('sport','a',fields.sport)];assert.equal(I.validateProposal({operation:'delete'},rows).operation,'ask');assert.equal(I.validateProposal({operation:'edit',targetIndex:9},rows).operation,'ask');assert.deepEqual(plain(I.validateProposal({operation:'edit',targetIndex:0},rows).targetIds),['a']);});
test('隐式表达可交模型复核，但输出仍只是建议',async()=>{const f=fixture(),I=f.get('record-intent'),S=f.get('journal-store'),records=[entry('sport','a',fields.sport)];let calls=0;const client={configured:true,routes:{chat:'test'},model:'fixture',request:async()=>{calls++;return result({operation:'edit',targetIndex:0});}};const r=await I.infer('那条用时应该多五分钟',{category:'sport',date:'2026-09-22',records},client);assert.equal(r.operation,'edit');assert.equal(calls,1);assert.equal(S.records().length,0);});
test('明确不保存时连意图API都不发送',async()=>{const I=fixture().get('record-intent');const r=await I.infer('不要记录',{category:'sport',date:'2026-09-22',records:[entry('sport','a',fields.sport)]},{configured:true,request:()=>{throw Error('must not call');}});assert.equal(r.operation,'none');});
test('中文UI保持原文，英文覆盖基础导航和设置',()=>{const f=fixture(),L=f.get('entry-i18n');for(const key of ['阿里云百炼','新增记录','修改记录','我的手记','这一段专注已结束'])assert.equal(L.t(key),key);L.setLanguage('en');for(const key of ['阿里云百炼','新增记录','修改记录','我的手记','这一段专注已结束'])assert.equal(/[\u3400-\u9fff]/.test(L.t(key)),false);});
test('英文展示投影不改变原记录',()=>{const f=fixture(),L=f.get('entry-i18n'),D=f.get('display-language'),r=entry('sport','a',fields.sport),original=JSON.stringify(r);L.setLanguage('en');assert.equal(D.record(r).data.activity,'Running');assert.equal(JSON.stringify(r),original);L.setLanguage('zh');assert.equal(D.record(r).data.activity,'跑步');});
test('未配置API时未知自由文本明确未翻译，不伪造英文含义',async()=>{const f=fixture(),L=f.get('entry-i18n'),D=f.get('display-language');L.setLanguage('en');await D.warm(['今天突然想起许久未见的朋友']);assert.equal(D.text('今天突然想起许久未见的朋友'),'Translation unavailable');});
test('只读翻译走实际协议、缓存复用、原库不变',async()=>{const f=fixture(),L=f.get('entry-i18n'),D=f.get('display-language'),S=f.get('journal-store');let calls=0;S.save(entry('mood','a',{mood:'今天读了 20 页',reason:'',notes:''}));const before=JSON.stringify(S.records());L.setLanguage('en');D.configure(()=>({configured:true,routes:{chat:'fixture'},model:'fixture',request:async(_,p)=>{calls++;assert.match(p.messages[0].content,/faithfully/);return result({translations:['I read 20 pages today']});}}));await D.warm(S.records());assert.equal(D.text('今天读了 20 页'),'I read 20 pages today');await D.warm(S.records());assert.equal(calls,1);assert.equal(JSON.stringify(S.records()),before);});
for(const invalid of [{translations:['I read 30 pages']},{translations:['读了20页']},{translations:[]},{translations:[null]}])test('翻译拒绝改数字/非英文/缺项 '+JSON.stringify(invalid),()=>{assert.throws(()=>fixture().get('display-language').validate(result(invalid),['我读20页']));});
test('英文AI回复不接受中文结果，中文模式仍可中文',()=>{const T=fixture().get('review-conversation'),r=result({replies:[{text:'我在听'}]});assert.throws(()=>T.parse(r,false,'en'));assert.equal(T.parse(r,false,'zh').replies[0].text,'我在听');});
test('英文记录提取要求英文自由文本，但枚举保留结构值',()=>{const f=fixture();f.get('entry-i18n').setLanguage('en');const text=f.get('ai-journal').prompt('food','photo');assert.match(text,/MUST be English/);assert.match(text,/canonical enum/);});
test('编辑按钮有明确保存修改，而非新增含义',()=>{const A=fixture().get('entry-action');assert.equal(A.describe({category:'sport',complete:true,editing:true,language:'en'}).label,'Save changes');assert.equal(A.describe({category:'sport',complete:true,editing:true,language:'zh'}).label,'保存修改');});
