/* 输入：发布源码与明确测试替身。输出：Node TAP。功能：验证路由、协议、取消与反馈，不调用真实AI。 */
const test = require('node:test'), assert = require('node:assert/strict'), vm = require('node:vm'), fs = require('node:fs'), path = require('node:path');
/** 输入：无。输出：隔离模块。功能：只使用内存存储，包含真正的v12客户端代码。 */
function setup() {
 const store = new Map();
 const c = vm.createContext({ Date, Intl, Math, Map, Set, WeakMap, Object, Array, Number, String, JSON, Error, TypeError, Promise, AbortController, DOMException, URL, TextEncoder, TextDecoder, Uint8Array, Response, performance, console, setTimeout, clearTimeout, requestAnimationFrame:()=>1, cancelAnimationFrame:()=>{}, localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}, fetch:async()=>{throw Error('Unexpected real request');} });
 vm.runInContext('const __fluffyModules={};',c);
 for(const f of ['ai-policy','cat-feedback','model','sleep-time','catalog','journal-store','entry-i18n','chat-stream','deepseek','bailian','ai-journal','review-data','chat-text','review-conversation','display-language','record-intent','speech','bubble-copy']) vm.runInContext(fs.readFileSync(path.join(__dirname,'../js',f+'.js'),'utf8'),c,{filename:f+'.js'});
 return {c,get:n=>vm.runInContext(`__fluffyModules[${JSON.stringify(n+'.js')}]`,c)};
}
/** 输入：对象/终止原因。输出：协议结果。功能：生成不含真实用户数据的模型返回替身。 */
function reply(data, finish='stop') { return {choices:[{finish_reason:finish,message:{content:typeof data==='string'?data:JSON.stringify(data)}}]}; }
/** 输入：fetch与可选超时。输出：启用测试Key的真实客户端。功能：只替换网络边界，不替换客户端校验。 */
function client(f, fetch, timeout) {const C=f.get('deepseek').DeepSeekClient, c=new C({fetchImpl:fetch,requestTimeoutMs:timeout});c.setKey('sk-fixture-not-a-real-secret');return c;}
const good = {fields:{activity:'跑步',durationMinutes:30,notes:'跑了5公里'},warnings:[]};
test('文本模型不必返回transcript：普通语音听写文本仍能回填',async()=>{const f=setup();let sent;const api=client(f,async(u,o)=>{sent=JSON.parse(o.body);return Response.json(reply(good));});const draft=await f.get('ai-journal').extract(api,'sport','跑步三十分钟，五公里');assert.equal(draft.fields.durationMinutes,30);assert.equal(draft.transcript,'跑步三十分钟，五公里');assert.equal(sent.thinking.type,'disabled');assert.equal(sent.response_format.type,'json_object');assert.equal(typeof sent.messages[1].content,'string');});
test('模型顶层白名单字段可兼容但不猜别名',()=>{const A=setup().get('ai-journal');assert.equal(A.sanitize({activity:'骑车',durationMinutes:20},'sport').fields.activity,'骑车');assert.throws(()=>A.sanitize({sportName:'骑车'},'sport'));});
test('部分有效字段不因未提供备注而丢弃',()=>{const d=setup().get('ai-journal').sanitize({fields:{activity:'游泳',durationMinutes:40}},'sport');assert.equal(d.fields.activity,'游泳');assert.equal(d.fields.notes,undefined);});
test('非有限/负时长不进入草稿，保留项目',()=>{for(const x of [-1,Infinity,'abc']){const d=setup().get('ai-journal').sanitize({fields:{activity:'跑步',durationMinutes:x}},'sport');assert.equal(d.fields.activity,'跑步');assert.equal(d.fields.durationMinutes,undefined);}});
test('情绪文本理解不假装分析了语调',async()=>{const f=setup(),api=client(f,async()=>Response.json(reply({fields:{mood:'可能有些失落'},emotion:{basis:'inferred',acousticEvidence:'假的音量'},warnings:[]})));const d=await f.get('ai-journal').extract(api,'mood','又白忙一天');assert.equal(d.emotion.acousticEvidence,'');assert.equal(d.emotion.needsConfirmation,true);});
test('语言任务禁止传入百炼客户端',async()=>{const f=setup();let calls=0;const b={provider:'bailian',configured:true,request:()=>{calls++}};await assert.rejects(f.get('ai-journal').extract(b,'sport','跑步'),e=>e.code==='deepseek-key');await assert.rejects(f.get('ai-journal').estimate(b,'任务',''),e=>e.code==='deepseek-key');assert.equal(calls,0);});
test('照片必须百炼，语言Key不能发送到视觉接口',async()=>{const f=setup(),api=client(f,async()=>{throw Error('must not request')});await assert.rejects(f.get('ai-journal').extract(api,'food','', 'data:image/jpeg;base64,abcd'),e=>e.code==='bailian-key');});
test('百炼视觉只发送照片和用户补充，不发送input_audio',async()=>{const f=setup();let payload;const b={provider:'bailian',configured:true,model:'qwen3-vl-plus',routes:{chat:'fixture'},request:async(_,p)=>{payload=p;return reply({fields:{foods:'米饭'},warnings:[]});}};await f.get('ai-journal').extract(b,'food','', 'data:image/jpeg;base64,abcd');assert.equal(payload.messages[1].content[1].type,'image_url');assert.ok(!JSON.stringify(payload).includes('input_audio'));});
test('旧的原始音频提取路径明确关闭，不再调用Omni',async()=>{const f=setup();await assert.rejects(f.get('ai-journal').extractAudio({provider:'bailian'}),e=>e.code==='speech-unsupported');});
test('同时提供百炼时，回顾文字仍只发送给DeepSeek',async()=>{const f=setup();let count=0;const api=client(f,async()=>{count++;return Response.json(reply({replies:[{text:'我在这里陪你',gesture:'soft'}]}));});const bailian={configured:true,provider:'bailian',request:()=>{throw Error('wrong provider')}};const v=f.get('review-data').build('sport','2026-09-22');await f.get('review-conversation').request({api,bailian,view:v,text:'今天有点累'});assert.equal(count,1);});
test('只有百炼Key时不自动接管回顾语言',async()=>{const f=setup();await assert.rejects(f.get('review-conversation').request({api:{configured:false},bailian:{configured:true},view:{}}),e=>e.code==='deepseek-key');});
test('原始音频不能混入回顾文字调用',async()=>{const f=setup();await assert.rejects(f.get('review-conversation').request({audio:{data:'fixture'}}),e=>e.code==='speech-unsupported');});
for(const [name,body,code] of [
 ['空正文',reply(''),'ai-empty'],['错误JSON',reply('{bad'),'ai-format'],['数组',reply('[]'),'ai-format'],['null',reply('null'),'ai-format'],['截断',reply(good,'length'),'ai-truncated'],['中断',reply(good,'aborted'),'ai-incomplete'],['拒绝',{choices:[{message:{refusal:'no'}}]},'ai-refused'],['危险键',reply('{"__proto__":{}}'),'ai-format']
])test('明确区分模型结果：'+name,()=>{assert.throws(()=>setup().get('ai-policy').json(body),e=>e.code===code);});
test('完整JSON代码围栏可识别',()=>{const P=setup().get('ai-policy');assert.equal(P.json(reply('```json\n{"fields":{"activity":"跑步"}}\n```')).fields.activity,'跑步');});
for(const [status,code] of [[400,'ai-parameter'],[401,'auth-deepseek'],[402,'ai-balance'],[403,'ai-permission'],[404,'ai-model'],[422,'ai-parameter'],[429,'ai-busy']])test('HTTP '+status+' 保留故障类别不泄漏上游正文',async()=>{const f=setup();let n=0;const api=client(f,async()=>{n++;return new Response('private upstream data',{status,headers:{'Retry-After':'60'}});});await assert.rejects(api.request(api.routes.chat,{},undefined),e=>e.code===code&&!e.message.includes('private'));assert.equal(n,1);});
test('503明确失败后只重试一次，然后成功',async()=>{const f=setup();let n=0;const api=client(f,async()=>++n===1?new Response('',{status:503,headers:{'Retry-After':'0'}}):Response.json(reply(good)));assert.ok(await api.request(api.routes.chat,{}));assert.equal(n,2);});
test('持续503最多两次，没有无限重试',async()=>{const f=setup();let n=0;const api=client(f,async()=>{n++;return new Response('',{status:503,headers:{'Retry-After':'0'}})});await assert.rejects(api.request(api.routes.chat,{}),e=>e.code==='ai-busy');assert.equal(n,2);});
test('未知网络故障不自动重复可能已经处理的请求',async()=>{const f=setup();let n=0;const api=client(f,async()=>{n++;throw new TypeError('Failed to fetch')});await assert.rejects(api.request(api.routes.chat,{}),e=>e.code==='ai-network');assert.equal(n,1);});
test('取消发生在请求前，连fetch都不会执行',async()=>{const f=setup();let n=0;const api=client(f,async()=>{n++});const c=new AbortController();c.abort();await assert.rejects(api.request(api.routes.chat,{},c.signal),e=>e.name==='AbortError');assert.equal(n,0);});
test('退避期间取消，不发送第二次',async()=>{const f=setup();let n=0;const api=client(f,async()=>{n++;return new Response('',{status:503,headers:{'Retry-After':'1'}})}),c=new AbortController();const task=api.request(api.routes.chat,{},c.signal);setTimeout(()=>c.abort(),15);await assert.rejects(task,e=>e.name==='AbortError');assert.equal(n,1);});
test('读取响应期间取消，迟到JSON也不能被使用',async()=>{const f=setup(),c=new AbortController();let finish;const api=client(f,async()=>({ok:true,json:()=>new Promise(r=>finish=r)}));const task=api.request(api.routes.chat,{},c.signal);await new Promise(r=>setTimeout(r,0));c.abort();finish(reply(good));await assert.rejects(task,e=>e.name==='AbortError');});
test('换Key后旧响应失效，不给新会话回填',async()=>{const f=setup();let finish;const api=client(f,async()=>({ok:true,json:()=>new Promise(r=>finish=r)}));const task=api.request(api.routes.chat,{});await new Promise(r=>setTimeout(r,0));api.setKey('sk-fixture-second-not-real');finish(reply(good));await assert.rejects(task,e=>e.name==='AbortError');});
test('超时退出而非无限思考',async()=>{const f=setup(),api=client(f,(_,o)=>new Promise((r,j)=>o.signal.addEventListener('abort',()=>j(new DOMException('aborted','AbortError')))),15);await assert.rejects(api.request(api.routes.chat,{}),e=>e.code==='ai-timeout');});
test('底层HTTP 200无效JSON仍是格式问题，不是没听清',async()=>{const f=setup(),api=client(f,async()=>({ok:true,json:async()=>{throw SyntaxError('bad')}}));await assert.rejects(api.request(api.routes.chat,{}),e=>e.code==='ai-format');});
test('错误气泡不引用下方提示，不伪装成整理成功',()=>{const f=setup();const r=f.get('bubble-copy').prepare(new (f.get('ai-policy').AIError)('ai-format','upstream private'),true);assert.equal(r.detail,'');assert.ok(!r.text.includes('下方'));assert.ok(!r.text.includes('填好'));assert.ok(!r.text.includes('upstream'));});
test('缺运动项目时有明确而自然的气泡询问',()=>{const f=setup(),r=f.get('bubble-copy').prepare('先填一下运动项目',true,{field:'activity'});assert.equal(r.text,'运动项目还空着\n说说做了什么呀');assert.equal(r.detail,'');});
test('所有内置故障提供纯英文且不回显敏感输入',()=>{const F=setup().get('cat-feedback');for(const key of Object.keys(F.COPY)){const v=F.say(key,{language:'en'});assert.ok(!/[\u3400-\u9fff]/.test(v),key);assert.ok(v.split('\n').length<=2,key);}assert.ok(!F.say(Error('sk-DO-NOT-SHOW-123456')).includes('DO-NOT-SHOW'));});
/** 输入：无。输出：模拟麦克风与真实SpeechSession。功能：只在外部识别边界发测试事件，不伪装实际听写成功。 */
function speechFixture() {
 const f=setup(),m=f.get('speech');let deviceStops=0, rec;
 class Context {constructor(){this.state='running'}async resume(){}createMediaStreamSource(){return {connect(){},disconnect(){}}}createAnalyser(){return {fftSize:32,getByteTimeDomainData:a=>a.fill(128)}}async close(){this.state='closed'}}
 class Recognition {constructor(){rec=this;}start(){this.onstart?.()}stop(){this.onend?.()}abort(){this.aborted=true}}
 const events=[];const s=new m.SpeechSession({onStarted:()=>events.push('started'),onError:e=>events.push(e),onLimit:()=>events.push('limit')},{Recognition,AudioContext:Context,mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop(){deviceStops++}}]})},stopWaitMs:15});
 const result=(text,final=true)=>{const row=[{transcript:text}];row.isFinal=final;rec.onresult?.({results:[row],resultIndex:0})};
 return {f,s,events,get rec(){return rec},result,stops:()=>deviceStops};
}
test('松手后等待最后转写，识别器和麦克风均释放',async()=>{const x=speechFixture();await x.s.start();x.rec.stop=()=>setTimeout(()=>{x.result('跑步三十分钟');x.rec.onend?.()},5);const r=await x.s.stop();assert.equal(r.text,'跑步三十分钟');assert.ok(x.stops()>0);assert.equal(x.s.recognition,null);x.s.cancel();});
test('只有临时尾句也保留并标记需核对',async()=>{const x=speechFixture();await x.s.start();x.result('跑步三十',false);const r=await x.s.stop();assert.equal(r.text,'跑步三十');assert.equal(r.interim,true);x.s.cancel();});
test('重复stop不会重复消费事件或发送内容',async()=>{const x=speechFixture();await x.s.start();x.result('跑步');const a=x.s.stop(),b=x.s.stop();assert.equal((await a).text,'跑步');assert.equal((await b).text,'跑步');x.s.cancel();});
test('空听写正确返回空文本，不生成范例',async()=>{const x=speechFixture();await x.s.start();const r=await x.s.stop();assert.equal(r.text,'');x.s.cancel();});
test('听写网络中断保留已经确定的原话',async()=>{const x=speechFixture();await x.s.start();x.result('跑步二十分钟');x.rec.onerror({error:'network'});const r=await x.s.stop();assert.equal(r.text,'跑步二十分钟');assert.equal(r.interrupted,true);assert.ok(x.events.includes('limit'));x.s.cancel();});
test('听写没有任何文字时网络错误不是没听清',async()=>{const x=speechFixture();await x.s.start();x.rec.onerror({error:'network'});assert.equal(x.events.find(e=>e&&e.code)?.code,'speech-network');assert.ok(x.stops()>0);x.s.cancel();});
test('取消后的旧识别事件不能更新下一轮',async()=>{const x=speechFixture();await x.s.start();const old=x.rec.onresult;x.s.cancel();const a=[{transcript:'迟到文字'}];a.isFinal=true;old({results:[a]});assert.equal(x.s.text(),'');});
/** 输入：可注入网络。输出：百炼客户端。功能：实际视觉客户端的隔离测试。 */
function visionClient(f,fetch){const c=new(f.get('bailian').BailianClient)({fetchImpl:fetch});c.setKey('sk-fixture-vision-key');return c;}
const imagePayload={messages:[{role:'user',content:[{type:'image_url',image_url:{url:'data:image/png;base64,AAAA'}}]}]};
test('百炼客户端自身拒绝纯文本任务',async()=>{const f=setup();let n=0;const c=visionClient(f,()=>{n++});await assert.rejects(c.request(c.routes.chat,{messages:[{role:'user',content:'你好'}]}),e=>e.code==='ai-parameter');assert.equal(n,0);});
test('百炼客户端自身拒绝图像请求混入原始录音',async()=>{const f=setup();let n=0;const c=visionClient(f,()=>{n++});await assert.rejects(c.request(c.routes.chat,{messages:[{role:'user',content:[...imagePayload.messages[0].content,{type:'input_audio',input_audio:{}}]}]}),e=>e.code==='ai-parameter');assert.equal(n,0);});
test('百炼视觉200坏JSON不被误报为网络或听写',async()=>{const f=setup(),c=visionClient(f,async()=>new Response('{bad'));await assert.rejects(c.request(c.routes.chat,imagePayload),e=>e.code==='ai-format');});
test('百炼换Key也使旧视觉结果失效',async()=>{const f=setup();let resolve;const c=visionClient(f,async()=>({ok:true,json:()=>new Promise(r=>resolve=r)}));const task=c.request(c.routes.chat,imagePayload);await new Promise(r=>setTimeout(r,0));c.setKey('sk-fixture-second-vision');resolve(reply({fields:{foods:'饭'}}));await assert.rejects(task,e=>e.name==='AbortError');});
test('百炼视觉401不泄漏上游正文',async()=>{const f=setup(),c=visionClient(f,async()=>new Response('private provider data',{status:401}));await assert.rejects(c.request(c.routes.chat,imagePayload),e=>e.code==='auth-bailian'&&!e.message.includes('private'));});
test('过深模型JSON受控拒绝，不发生无限递归',()=>{let body={};for(let i=0;i<48;i++)body={nested:body};assert.throws(()=>setup().get('ai-policy').json(reply(body)),e=>e.code==='ai-format');});
test('成功恢复布局不误说成服务故障',()=>{const F=setup().get('cat-feedback');assert.equal(F.classify('布局已恢复。'),'layout-restored');assert.ok(!F.say('布局已恢复。').includes('没能'));});
test('失败的保存/删除/分享不误说成成功',()=>{const F=setup().get('cat-feedback');for(const [t,k] of [['删除失败，记录仍保留。','delete-failed'],['目标未能保存，请重试','save-failed'],['分享未完成，可以保存图片','share-failed']])assert.equal(F.classify(t),k);});
